PROJECT = earth_defender
PROJECT_DESCRIPTION = Earth Defender game server
PROJECT_VERSION = 1.0.0
PROJECT_REGISTERED = global_rooms_state
PROJECT_MOD = earth_defender_app

ERLC_OPTS = +nowarn_export_vars

DEPS = cowboy jiffy
dep_cowboy_commit = master

include erlang.mk
